import Color from 'color';
import EStyleSheet from 'react-native-extended-stylesheet';
import {margin} from './modules/margin';
import {padding} from './modules/padding';
import {flexbox} from './modules/flexbox';
import {layout} from './modules/layout';
import {border} from './modules/border';
import {background} from './modules/background';

/**
 * More info about extended stylesheet visit:
 * @link https://github.com/vitalets/react-native-extended-stylesheet
 */

const defaultClasses = () => ({

  'btn-block': {flex: 1},
  'link': {textDecorationLine: 'underline', color: '$primary'},
  'btn-padding': {paddingHorizontal: '$btnPaddingHorizontal', paddingVertical: '$btnPaddingVertical'},
  'btn-sm': {paddingHorizontal: '$btnPaddingHorizontal * 0.64', paddingVertical: '$btnPaddingVertical * 0.64'},
  'btn-md': {paddingHorizontal: '$btnPaddingHorizontal * 1.24', paddingVertical: '$btnPaddingVertical * 1.24'},
  'btn-lg': {paddingHorizontal: '$btnPaddingHorizontal * 1.48', paddingVertical: '$btnPaddingVertical * 1.48'},
  'btn-xl': {paddingHorizontal: '$btnPaddingHorizontal * 1.64', paddingVertical: '$btnPaddingVertical * 1.64'},
  'btn-2xl': {paddingHorizontal: '$btnPaddingHorizontal * 1.96', paddingVertical: '$btnPaddingVertical * 1.96'},
  'btn-3xl': {paddingHorizontal: '$btnPaddingHorizontal * 2.24', paddingVertical: '$btnPaddingVertical * 2.24'},
  'btn': {
    backgroundColor: '$primary',
    borderWidth: 1,
    borderColor: Color(EStyleSheet.value('$primary')).lighten(0.32).hex(),
    borderRadius: 5,
    paddingHorizontal: '$btnPaddingHorizontal',
    paddingVertical: '$btnPaddingVertical',
  },
  'card': {
    backgroundColor: Color(EStyleSheet.value('$bgBody')).lighten(0.2).hex(),
    borderRadius: 5,
    shadowOpacity: 0.16,
    shadowRadius: 4,
    shadowOffset: {height: 4, width: 0},
    elevation: 4,
  },

  'bg-body': {backgroundColor: '$bgBody'},
  'bg-popover': {backgroundColor: Color(EStyleSheet.value('$bgBody')).lighten(0.75).hex()},
  'bg-panel': {backgroundColor: Color(EStyleSheet.value('$bgBody')).lighten(0.4).hex()},
  'bg-panel-50': {backgroundColor: Color(EStyleSheet.value('$bgBody')).lighten(0.2).hex()},
  'justify-content-between': {justifyContent: 'space-between'},
  'align-items-start': {justifyContent: 'flex-start'},
  'align-items-end': {justifyContent: 'flex-end'},
  'align-items-center': {justifyContent: 'center', alignItems: 'stretch'},
  'align-self-start': {alignSelf: 'flex-start'},
  'align-self-center': {alignSelf: 'center'},
  'align-self-end': {alignSelf: 'flex-end'},
  'justify-content-center': {justifyContent: 'center'},
  'input-active': {borderWidth: 1, borderColor: '$primary'},
  'input-error': {borderWidth: 1, borderColor: '$danger'},
  'input': {borderWidth: 1, borderColor: '$gray2', paddingHorizontal: '1rem', paddingVertical: '0.75rem', margin: 0},
  'text-area': {
    borderWidth: 1,
    borderColor: '$gray2',
    paddingHorizontal: '1rem',
    paddingVertical: '0.75rem',
    margin: 0,
    maxHeight: 100,
  },
  'col': {flex: 1, flexDirection: 'column'},
  'col-auto': {flexDirection: 'column'},
  'col-1': {flex: 1},
  'col-10': {flex: 10},
  'col-11': {flex: 11},
  'col-12': {flex: 12},
  'col-2': {flex: 2},
  'col-3': {flex: 3},
  'col-4': {flex: 4},
  'col-5': {flex: 5},
  'col-6': {flex: 6},
  'col-7': {flex: 7},
  'col-8': {flex: 8},
  'col-9': {flex: 9},
  'row': {flexDirection: 'row'},
  'shadow': {shadowOpacity: 0.16, shadowRadius: 4, shadowOffset: {height: 4, width: 0}, elevation: 4},
  'shadow-sm': {shadowOpacity: 0.16, shadowRadius: 2, shadowOffset: {height: 2, width: 0}, elevation: 2},
  'shadow-md': {shadowOpacity: 0.16, shadowRadius: 6, shadowOffset: {height: 6, width: 0}, elevation: 6},
  'shadow-lg': {shadowOpacity: 0.16, shadowRadius: 8, shadowOffset: {height: 8, width: 0}, elevation: 8},
  'shadow-none': {shadowOpacity: 0, shadowRadius: 0, shadowOffset: {height: 0, width: 0}, elevation: 0},
  'tab': {marginBottom: -1},
  'tab-active': {marginBottom: -1},
  'tab-inactive': {marginTop: -1, borderBottomWidth: 1},
  'bottom-15': {bottom: '15rem'},
  'bottom-13': {bottom: '13rem'},
  'position-absolute': {position: 'absolute'},
  'top-15': {top: '15rem'},
  'top-13': {top: '13rem'},
  'p-half': {padding: '0.5rem'},
  'py-1-half': {padding: '1.5rem'},
  'py-half': {paddingVertical: '0.5rem'},
  'py-0.75': {paddingVertical: '0.75rem'},
  'px-half': {paddingHorizontal: '0.5rem'},
  'px-1-half': {paddingHorizontal: '1.5rem'},
  'pt-half': {paddingTop: '0.5rem'},
  'pr-half': {paddingRight: '0.5rem'},
  'pr-1-half': {paddingRight: '1.5rem'},
  'pb-half': {paddingBottom: '0.5rem'},
  'pl-half': {paddingLeft: '0.5rem'},
  'text-justify': {textAlign: 'justify'},
  'text': {fontFamily: '$defaultFontFamily', fontSize: '1rem', color: '$text'},
  'text-blue': {color: '$blue'},
  'text-indigo': {color: '$indigo'},
  'text-purple': {color: '$purple'},
  'text-pink': {color: '$pink'},
  'text-red': {color: '$red'},
  'text-orange': {color: '$orange'},
  'text-yellow': {color: '$yellow'},
  'text-green': {color: '$green'},
  'text-teal': {color: '$teal'},
  'text-cyan': {color: '$cyan'},
  'text-gray': {color: '$gray'},
  'text-primary': {color: '$primary'},
  'text-secondary': {color: '$secondary'},
  'text-success': {color: '$success'},
  'text-info': {color: '$info'},
  'text-warning': {color: '$warning'},
  'text-danger': {color: '$danger'},
  'text-white': {color: '$white'},
  'text-dark': {color: '$dark'},
  'text-black': {color: '$black'},
  'text-light': {color: '$textLight'},
  'text-gray-1': {color: '$gray1'},
  'text-gray-2': {color: '$gray2'},
  'text-gray-3': {color: '$gray3'},
  'text-gray-4': {color: '$gray4'},
  'text-gray-5': {color: '$gray5'},
  'text-gray-dark': {color: '$grayDark'},
  'text-50': {color: Color(EStyleSheet.value('$text')).lighten(0.5).hex()},
  'text-light-50': {color: Color(EStyleSheet.value('$textLight')).lighten(0.75).hex()},
  'h1': {
    fontFamily: '$defaultFontFamily',
    fontSize: '3rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h2': {
    fontFamily: '$defaultFontFamily',
    fontSize: '2.5rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h3': {
    fontFamily: '$defaultFontFamily',
    fontSize: '2rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h4': {
    fontFamily: '$defaultFontFamily',
    fontSize: '1.6rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h5': {
    fontFamily: '$defaultFontFamily',
    fontSize: '1.2rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h6': {
    fontFamily: '$defaultFontFamily',
    fontSize: '1rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'text-center': {textAlign: 'center'},
  'statusbar-space': {},
  'col-reverse': {flexDirection: 'column-reverse'},
  'row-reverse': {flexDirection: 'row-reverse'},
  'flex-end': {alignItems: 'flex-end'},
  'flex-start': {alignItems: 'flex-start'},
  'flex-grow': {flexGrow: 1},
  'flex-remove': {flex: 0, flexGrow: 0},
  'inline': {alignSelf: 'flex-start', position: 'relative'},
  'align-right': {alignSelf: 'flex-end'},
  'text-xs': {fontSize: '0.75rem', fontWeight: '500'},
  'text-sm': {fontSize: '0.875rem', fontWeight: '500'},
  'text-md': {fontSize: '1.48rem'},
  'text-lg': {fontSize: '1.125rem'},
  'text-xl': {fontSize: '1.25rem'},
  'text-2xl': {fontSize: '1.5rem'},
  'text-3xl': {fontSize: '1.875rem'},
  'text-title': {fontSize: '1.8rem'},
  'text-subtitle': {fontSize: '1.4rem'},
  'text-btn': {fontSize: '1.16rem'},
  'text-bold': {fontWeight: 'bold'},
  'text-disabled': {color: Color(EStyleSheet.value('$textLight')).lighten(0.5).hex()},
  'text-link': {textDecorationLine: 'underline'},
  'text-align-left': {textAlign: 'left'},
  'text-align-right': {textAlign: 'right'},
  'text-align-center': {textAlign: 'center'},
  'icon': {fontSize: '1.5rem'},
  'icon-xxs': {fontSize: '0.75rem'},
  'icon-xs': {fontSize: '1rem'},
  'icon-sm': {fontSize: '1.2rem'},
  'icon-md': {fontSize: '2rem'},
  'icon-lg': {fontSize: '2.35rem'},
  'icon-xl': {fontSize: '3rem'},
  'icon-2xl': {fontSize: '4rem'},
  'icon-3xl': {fontSize: '8rem'},
  'logo-smt-drawer': {fontSize: '6rem'},
  'icon-fullscreen': {fontSize: '12rem'},
  'w-auto': {width: 'auto'},
  'w-half': {width: '0.5rem'},
  'w-1': {width: '1rem'},
  'w-1-half': {width: '1.5rem'},
  'w-2': {width: '2rem'},
  'w-3': {width: '3rem'},
  'w-4': {width: '4rem'},
  'w-5': {width: '5rem'},
  'w-6': {width: '6rem'},
  'w-7': {width: '7rem'},
  'w-8': {width: '8rem'},
  'w-9': {width: '9rem'},
  'w-10': {width: '10rem'},
  'w-11': {width: '11rem'},
  'w-12': {width: '12rem'},
  'w-13': {width: '13rem'},
  'w-14': {width: '14rem'},
  'w-15': {width: '15rem'},
  'w-16': {width: '16rem'},
  'w-17': {width: '17rem'},
  'w-18': {width: '18rem'},
  'w-19': {width: '19rem'},
  'w-20': {width: '20rem'},
  'w-21': {width: '21rem'},
  'w-22': {width: '22rem'},
  'w-23': {width: '23rem'},
  'w-24': {width: '24rem'},
  'w-25-p': {width: '25%'},
  'w-50-p': {width: '50%'},
  'w-100-p': {width: '100%'},
  'h-half': {height: '0.5rem'},
  'h-1': {height: '1rem'},
  'h-1-half': {height: '1.5rem'},
  'h-2': {height: '2rem'},
  'h-3': {height: '3rem'},
  'h-4': {height: '4rem'},
  'h-5': {height: '5rem'},
  'h-6': {height: '6rem'},
  'h-7': {height: '7rem'},
  'h-8': {height: '8rem'},
  'h-9': {height: '9rem'},
  'h-10': {height: '10rem'},
  'h-12': {height: '12rem'},
  'h-15': {height: '15rem'},
  'h-16': {height: '16rem'},
  'h-20': {height: '20rem'},
  'h-21': {height: '21rem'},
  'h-22': {height: '22rem'},
  'w-max-1': {maxWidth: '1rem'},
  'w-max-2': {maxWidth: '2rem'},
  'w-max-3': {maxWidth: '3rem'},
  'w-max-4': {maxWidth: '4rem'},
  'w-max-5': {maxWidth: '5rem'},
  'w-max-6': {maxWidth: '6rem'},
  'w-max-7': {maxWidth: '7rem'},
  'w-max-8': {maxWidth: '8rem'},
  'w-max-9': {maxWidth: '9rem'},
  'w-max-10': {maxWidth: '10rem'},
  'w-max-11': {maxWidth: '11rem'},
  'w-max-12': {maxWidth: '12rem'},
  'w-max-13': {maxWidth: '13rem'},
  'w-max-14': {maxWidth: '14rem'},
  'w-max-15': {maxWidth: '15rem'},
  'w-max-16': {maxWidth: '16rem'},
  'w-max-24': {maxWidth: '24rem'},
  'w-min-1': {minWidth: '1rem'},
  'w-min-2': {minWidth: '2rem'},
  'w-min-3': {minWidth: '3rem'},
  'w-min-4': {minWidth: '4rem'},
  'w-min-5': {minWidth: '5rem'},
  'w-min-6': {minWidth: '6rem'},
  'w-min-7': {minWidth: '7rem'},
  'w-min-8': {minWidth: '8rem'},
  'w-min-9': {minWidth: '9rem'},
  'w-min-10': {minWidth: '10rem'},
  'w-min-11': {minWidth: '11rem'},
  'w-min-12': {minWidth: '12rem'},
  'w-min-13': {minWidth: '13rem'},
  'w-min-14': {minWidth: '14rem'},
  'w-min-15': {minWidth: '15rem'},
  'w-min-16': {minWidth: '16rem'},
  'h-min-1': {minHeight: '1rem'},
  'h-min-2': {minHeight: '2rem'},
  'h-min-3': {minHeight: '3rem'},
  'h-min-4': {minHeight: '4rem'},
  'h-min-5': {minHeight: '5rem'},
  'h-min-6': {minHeight: '6rem'},
  'h-min-7': {minHeight: '7rem'},
  'h-min-8': {minHeight: '8rem'},
  'h-min-9': {minHeight: '9rem'},
  'h-min-10': {minHeight: '10rem'},
  'h-min-11': {minHeight: '11rem'},
  'h-min-12': {minHeight: '12rem'},
  'h-min-13': {minHeight: '13rem'},
  'h-min-14': {minHeight: '14rem'},
  'h-min-15': {minHeight: '15rem'},
  'h-min-16': {minHeight: '16rem'},
  'm-half': {margin: '0.5rem'},
  'my-half': {marginVertical: '0.5rem'},
  'mx-half': {marginHorizontal: '0.5rem'},
  'mt-half': {marginTop: '0.5rem'},
  'mt-q3': {marginTop: '0.75rem'},
  '-mt-half': {marginTop: '-0.5rem'},
  '-m-half': {margin: '-0.5rem'},
  'mr-half': {marginRight: '0.5rem'},
  'mr-1-half': {marginRight: '1.5rem'},
  'mb-half': {marginBottom: '0.5rem'},
  '-mb-half': {marginBottom: '-0.5rem'},
  '-ml-half': {marginLeft: '-0.5rem'},
  'ml-half': {marginLeft: '0.5rem'},
  'img': {aspectRatio: 1, height: 'auto'},
  'img-4-9': {aspectRatio: 4 / 9, height: 'auto'},
  'img-16-9': {aspectRatio: 16 / 9, height: 'auto'},
  'img-9-4': {aspectRatio: 9 / 4, height: 'auto'},
  'img-9-16': {aspectRatio: 9 / 16, height: 'auto'},
  'center': {alignItems: 'center', justifyContent: 'center'},
  'b-transparent': {borderColor: 'transparent'},
  'b-blue': {borderColor: '$blue'},
  'b-indigo': {borderColor: '$indigo'},
  'b-purple': {borderColor: '$purple'},
  'b-pink': {borderColor: '$pink'},
  'b-red': {borderColor: '$red'},
  'b-orange': {borderColor: '$orange'},
  'b-yellow': {borderColor: '$yellow'},
  'b-green': {borderColor: '$green'},
  'b-teal': {borderColor: '$teal'},
  'b-cyan': {borderColor: '$cyan'},
  'b-gray': {borderColor: '$gray'},
  'b-gray-1': {borderColor: '$gray1'},
  'b-gray-2': {borderColor: '$gray2'},
  'b-gray-3': {borderColor: '$gray3'},
  'b-gray-4': {borderColor: '$gray4'},
  'b-gray-5': {borderColor: '$gray5'},
  'b-grayDark': {borderColor: '$grayDark'},
  'b-primary': {borderColor: '$primary'},
  'b-secondary': {borderColor: '$secondary'},
  'b-success': {borderColor: '$success'},
  'b-info': {borderColor: '$info'},
  'b-warning': {borderColor: '$warning'},
  'b-danger': {borderColor: '$danger'},
  'b-white': {borderColor: '$white'},
  'b-light': {borderColor: '$light'},
  'b-dark': {borderColor: '$dark'},
  'b-black': {borderColor: '$black'},
  'badge-fixed': {position: 'absolute', right: '-1rem', top: '-1rem'},
  'badge': {
    backgroundColor: '$primary',
    padding: '0.5rem',
    marginVertical: 1,
    borderRadius: '9999rem',
    minWidth: '2.5rem',
    color: '$white',
    fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  'badge-sm': {
    backgroundColor: '$primary',
    padding: '0.25rem',
    marginVertical: 1,
    borderRadius: 14,
    minWidth: '1.5rem',
    color: '$white',
    fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  'bl-0': {borderLeftWidth: 0, borderColor: 'transparent'},
  'br-0': {borderRightWidth: 0, borderColor: 'transparent'},
  'b-0': {borderWidth: 0, borderColor: 'transparent'},
  'b-1': {borderWidth: 1, borderColor: '$gray2'},
  'b-2': {borderWidth: 2, borderColor: '$gray2'},
  'bt-1': {borderTopWidth: 1, borderColor: '$gray2'},
  'br-1': {borderRightWidth: 1, borderColor: '$gray2'},
  'bb-0': {borderBottomWidth: 0},
  'bb-1': {borderBottomWidth: 1, borderColor: '$gray2'},
  'bl-1': {borderLeftWidth: 1, borderColor: '$gray2'},
  'bx-1': {borderLeftWidth: 1, borderRightWidth: 1, borderColor: '$gray2'},
  'by-1': {borderTopWidth: 1, borderBottomWidth: 1, borderColor: '$gray2'},
  'bt-2': {borderTopWidth: 2, borderColor: '$gray2'},
  'br-2': {borderRightWidth: 2, borderColor: '$gray2'},
  'bb-2': {borderBottomWidth: 2, borderColor: '$gray2'},
  'bl-2': {borderLeftWidth: 2, borderColor: '$gray2'},
  'bx-2': {borderLeftWidth: 2, borderRightWidth: 2, borderColor: '$gray2'},
  'by-2': {borderBottomWidth: 2, borderTopWidth: 2, borderColor: '$gray2'},
  'bt-3': {borderTopWidth: 3, borderColor: '$gray2'},
  'br-3': {borderRightWidth: 3, borderColor: '$gray2'},
  'bb-3': {borderBottomWidth: 3, borderColor: '$gray2'},
  'bl-3': {borderLeftWidth: 3, borderColor: '$gray2'},
  'bx-3': {borderLeftWidth: 3, borderRightWidth: 3, borderColor: '$gray2'},
  'by-3': {borderBottomWidth: 3, borderTopWidth: 3, borderColor: '$gray2'},
  'bt-4': {borderTopWidth: 4, borderColor: '$gray2'},
  'br-4': {borderRightWidth: 4, borderColor: '$gray2'},
  'bb-4': {borderBottomWidth: 4, borderColor: '$gray2'},
  'bl-4': {borderLeftWidth: 4, borderColor: '$gray2'},
  'bx-4': {borderLeftWidth: 4, borderRightWidth: 4, borderColor: '$gray2'},
  'by-4': {borderBottomWidth: 4, borderTopWidth: 4, borderColor: '$gray2'},
  'bt-5': {borderTopWidth: 5, borderColor: '$gray2'},
  'br-5': {borderRightWidth: 5, borderColor: '$gray2'},
  'bb-5': {borderBottomWidth: 5, borderColor: '$gray2'},
  'bl-5': {borderLeftWidth: 5, borderColor: '$gray2'},
  'bx-5': {borderLeftWidth: 5, borderRightWidth: 5, borderColor: '$gray2'},
  'by-5': {borderBottomWidth: 5, borderTopWidth: 5, borderColor: '$gray2'},
  'bt-6': {borderTopWidth: 6, borderColor: '$gray2'},
  'br-6': {borderRightWidth: 6, borderColor: '$gray2'},
  'bb-6': {borderBottomWidth: 6, borderColor: '$gray2'},
  'bl-6': {borderLeftWidth: 6, borderColor: '$gray2'},
  'bx-6': {borderLeftWidth: 6, borderRightWidth: 6, borderColor: '$gray2'},
  'by-6': {borderBottomWidth: 6, borderTopWidth: 6, borderColor: '$gray2'},
  'z-index-min': {position: 'absolute', zIndex: 0},
  'z-index-max': {position: 'absolute', zIndex: 9999},
  'mh-input': {minHeight: '3rem'},
  'right-13': {right: '13rem'},
  'right-15': {right: '15rem'},
  '-right-half': {right: '-0.5rem'},
  '-right-1': {right: '-1rem'},
  '-right-2': {right: '-2rem'},
  '-right-3': {right: '-3rem'},
  '-right-4': {right: '-4rem'},
  '-right-5': {right: '-5rem'},
  '-right-6': {right: '-6rem'},
  '-right-7': {right: '-7rem'},
  '-right-8': {right: '-8rem'},
  '-right-9': {right: '-9rem'},
  '-right-10': {right: '-10rem'},
  '-right-11': {right: '-11rem'},
  '-right-12': {right: '-12rem'},
  '-right-13': {right: '-13rem'},
  '-right-14': {right: '-14rem'},
  '-right-15': {right: '-15rem'},
  '-right-16': {right: '-16rem'},
  'left-13': {left: '13rem'},
  'left-15': {left: '15rem'},
  'list-item': {alignSelf: 'center', maxWidth: '48rem', width: '100%'},
  'transparent': {opacity: 0},
  'disabled': {opacity: 0.32},
  'p-tag': {paddingHorizontal: '0.5rem', paddingVertical: '0.25rem'},
  'p-tag-sm': {paddingHorizontal: '0.48rem', paddingVertical: '0.24rem'},

  ...background,
  ...border,
  ...layout,
  ...flexbox,
  ...padding,
  ...margin,

// 'test': {placeContent: 'auto'},
});

/**
 * TODO: replace scaleY with transform
 */
// 'invert': scaleY: -1,

export default defaultClasses;
